# Default values for my-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates. !

replicaCount: 1
image:
  repository: georgesmomo/node-hello-world # Ce sera le nom de notre image
  pullPolicy: IfNotPresent
  # Overridden by the CI/CD pipeline
  tag: "1.0.0-develop.46.dd164c4"
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort # <--- Change ici
  port: 80
  nodePort: 31000 # <--- Ajoute ceci (entre 30000 et 32767)
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
resources:
  # Nous recommandons de ne pas décommenter ces lignes, mais de les laisser comme
  # un guide pour l'utilisateur. Définissez-les dans un fichier values spécifique à l'environnement.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
persistence:
  enabled: false
  # storageClass: "standard" # Ou le nom de votre StorageClass
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 1Gi
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false
  # Autres valeurs d’ingress si nécessaire, par ex :
  # hosts:
  #   - host: example.com
  #     paths: ["/"]
autoscaling:
  enabled: false
  # autres valeurs si nécessaires
